# Configuration for App 1 (Frontend)
appOne:
  name: frontend-app
  replicas: 2
  image: nginx:latest
  containerPort: 80
  servicePort: 80

# Configuration for App 2 (Backend)
appTwo:
  name: backend-app
  replicas: 2
  image: httpd:latest
  containerPort: 80
  servicePort: 8080

# Global Ingress Configuration
ingress:
  enabled: true
  className: nginx
  host: a4f11bdac1def43108b214a9b0ca3f23-1441482269.ap-south-2.elb.amazonaws.com

# Custom HTML Content
htmlContent:
  frontend: |
    <!DOCTYPE html>
    <html>
    <head><title>Frontend App</title></head>
    <body><h1>Welcome to the Frontend Application!</h1></body>
    </html>
  backend: |
    <!DOCTYPE html>
    <html>
    <head><title>Backend API</title></head>
    <body><h1>Welcome to the Backend API Stub!</h1></body>
    </html>

